#!/usr/bin/env node
/* gen_vectors.js — interrogate the JS reference core and emit vectors.h
 * so test_chakra.c can verify the C port value-for-value.
 * Copyright (C) 1993-2026 Abhishek Choudhary. GPL-3.0-or-later. */
"use strict";
const C = require("../src/chakra-core.js");
const TZN=["Imix","Ik","Akbal","Kan","Chicchan","Cimi","Manik","Lamat","Muluc","Oc","Chuen","Eb","Ben","Ix","Men","Cib","Caban","Etznab","Cauac","Ahau"];


let s = 42;
const rnd = () => (s = (s * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff;

const fmt = (x) => {
  if (typeof x === "number") {
    if (Number.isInteger(x) && Math.abs(x) < 1e15) return String(x);
    return x.toPrecision(17);
  }
  return JSON.stringify(x);
};
const arr = (name, type, xs) =>
  `static const ${type} ${name}[]={${xs.map(fmt).join(",")}};\n`;

let out = "";
out += "/* AUTO-GENERATED by gen_vectors.js from ../src/chakra-core.js — do not edit. */\n";
out += "/* Copyright (C) 1993-2026 Abhishek Choudhary. GPL-3.0-or-later. No warranty. */\n";
out += `/* reference core version: ${C.version} */\n\n`;

/* ── ephemeris samples ─────────────────────────────────────────────── */
const NV = 160;
const D = [], SUN = [], MOO = [], MLAT = [], PY = [];
const PL = { Mercury: [], Venus: [], Mars: [], Jupiter: [], Saturn: [], Uranus: [], Neptune: [] };
const RAHU = [], ASC = [], MCV = [], GM = [], OB = [], AY = [];
const ELG = [], ILL = [], VARA = [], TITH = [], NAKI = [], YOGI = [], KARI = [], MANI = [];
const LAT = 17.385, LON = 78.486;
for (let i = 0; i < NV; i++) {
  const d = -3652 + rnd() * 21914; /* ≈1990–2050 */
  const y = 2000 + d / 365.25;
  D.push(d); PY.push(y);
  SUN.push(C.sunLon(d).lon); MOO.push(C.moonLon(d)); MLAT.push(C.moonLatf(d));
  for (const n of Object.keys(PL)) PL[n].push(C.planetLon(n, d));
  RAHU.push(C.rev(C.ELEM.Moon(d).N));
  ASC.push(C.ascendant(d, LAT, LON)); MCV.push(C.mcLon(d, LON));
  GM.push(C.gmst(d)); OB.push(C.obliq(d)); AY.push(C.ayan(y));
  const ph = C.phaseInfo(d); ELG.push(ph.elong); ILL.push(ph.illum);
  const p = C.panchanga(d, y);
  VARA.push(C.VARA.indexOf(p.vara));
  TITH.push(p.tithiIndex);
  NAKI.push(p.nakIndex);
  YOGI.push(C.YOGA.indexOf(p.yoga));
  KARI.push(Math.floor(C.rev(C.moonLon(d) - C.sunLon(d).lon) / 6));
  MANI.push(C.MANAZIL.indexOf(p.manzil));
}
out += `#define NV ${NV}\n`;
out += arr("V_d", "double", D) + arr("V_py", "double", PY);
out += arr("V_sun", "double", SUN) + arr("V_moon", "double", MOO) + arr("V_mlat", "double", MLAT);
out += arr("V_merc", "double", PL.Mercury) + arr("V_ven", "double", PL.Venus) + arr("V_mar", "double", PL.Mars);
out += arr("V_jup", "double", PL.Jupiter) + arr("V_sat", "double", PL.Saturn);
out += arr("V_ura", "double", PL.Uranus) + arr("V_nep", "double", PL.Neptune);
out += arr("V_rahu", "double", RAHU);
out += arr("V_asc", "double", ASC) + arr("V_mcv", "double", MCV);
out += arr("V_gmst", "double", GM) + arr("V_obl", "double", OB) + arr("V_ayan", "double", AY);
out += arr("V_elong", "double", ELG) + arr("V_illum", "double", ILL);
out += arr("V_vara", "int", VARA) + arr("V_tith", "int", TITH) + arr("V_naki", "int", NAKI);
out += arr("V_yogi", "int", YOGI) + arr("V_kari", "int", KARI) + arr("V_mani", "int", MANI);
out += `static const double V_lat=${LAT}, V_lon=${LON};\n\n`;

/* ── calendar samples on civil JDNs ────────────────────────────────── */
const NJ = 90;
const J = [], SUY = [], SUM = [], SUD = [], SHY = [], SHM = [], SHD = [];
const HBY = [], HBM = [], HBD = [], HBL = [];
const NKY = [], NKM = [], NKD = [];
const MBK = [], MKT = [], MTN = [], MUN = [], MKI = [], MTZ = [], MTI = [], MHD = [], MHM = [];
const CST = [], CBR = [], KUY = [], KUM = [], KUD = [];
for (let i = 0; i < NJ; i++) {
  const j = 2451545 + Math.floor(rnd() * 13000);
  J.push(j);
  const su = C.hijriSunni(j); SUY.push(su.y); SUM.push(su.m); SUD.push(su.d);
  const sh = C.hijriShia(j); SHY.push(sh.y); SHM.push(sh.m); SHD.push(sh.d);
  const h = C.hebrew(j); HBY.push(h.y); HBM.push(h.monthIndex); HBD.push(h.d); HBL.push(h.leap ? 1 : 0);
  const nk = C.nanakshahi(j); NKY.push(nk.y); NKM.push(nk.monthIndex); NKD.push(nk.d);
  const my = C.mayan(j);
  const lc = my.lc.split(".").map(Number);
  MBK.push(lc[0]); MKT.push(lc[1]); MTN.push(lc[2]); MUN.push(lc[3]); MKI.push(lc[4]);
  const tz = my.tz.split(" "); MTZ.push(+tz[0]); MTI.push(TZN.indexOf(tz[1]));
  const hb = my.haab.split(" "); MHD.push(+hb[0]); MHM.push(["Pop","Wo","Sip","Sotz","Sek","Xul","Yaxkin","Mol","Chen","Yax","Sak","Keh","Mak","Kankin","Muwan","Pax","Kayab","Kumku","Wayeb"].indexOf(hb[1]));
  const g = C.jdn2greg(j);
  CST.push(((g.Y - 4) % 10 + 10) % 10); CBR.push(((g.Y - 4) % 12 + 12) % 12);
  const ku = C.greg2hijri(j); KUY.push(ku[0]); KUM.push(ku[1]); KUD.push(ku[2]);
}
out += `#define NJ ${NJ}\n`;
out += arr("V_j", "long", J);
out += arr("V_suy", "int", SUY) + arr("V_sum", "int", SUM) + arr("V_sud", "int", SUD);
out += arr("V_shy", "int", SHY) + arr("V_shm", "int", SHM) + arr("V_shd", "int", SHD);
out += arr("V_hby", "int", HBY) + arr("V_hbm", "int", HBM) + arr("V_hbd", "int", HBD) + arr("V_hbl", "int", HBL);
out += arr("V_nky", "int", NKY) + arr("V_nkm", "int", NKM) + arr("V_nkd", "int", NKD);
out += arr("V_mbk", "long", MBK) + arr("V_mkt", "int", MKT) + arr("V_mtn", "int", MTN) + arr("V_mun", "int", MUN) + arr("V_mki", "int", MKI);
out += arr("V_mtz", "int", MTZ) + arr("V_mti", "int", MTI) + arr("V_mhd", "int", MHD) + arr("V_mhm", "int", MHM);
out += arr("V_cst", "int", CST) + arr("V_cbr", "int", CBR);
out += arr("V_kuy", "int", KUY) + arr("V_kum", "int", KUM) + arr("V_kud", "int", KUD) + "\n";

/* ── solvers ───────────────────────────────────────────────────────── */
const SE_T0 = [], SE_TG = [], SE_R = [];
for (let i = 0; i < 10; i++) { const t0 = -3000 + rnd() * 15000, tg = Math.floor(rnd() * 12) * 30; SE_T0.push(t0); SE_TG.push(tg); SE_R.push(C.solveElong(t0, tg)); }
out += `#define NSE 10\n` + arr("V_se_t0", "double", SE_T0) + arr("V_se_tg", "double", SE_TG) + arr("V_se_r", "double", SE_R);
const SA_T0 = [], SA_TG = [], SA_R = [];
for (let i = 0; i < 4; i++) { const t0 = 8000 + rnd() * 2000, tg = rnd() * 360; SA_T0.push(t0); SA_TG.push(tg); SA_R.push(C.solveAsc(t0, tg, LAT, LON)); }
out += `#define NSA 4\n` + arr("V_sa_t0", "double", SA_T0) + arr("V_sa_tg", "double", SA_TG) + arr("V_sa_r", "double", SA_R);

/* mesha / nowruz */
const MY = [2000, 2010, 2020, 2026, 2035, 2049];
out += `#define NMY ${MY.length}\n` + arr("V_my", "int", MY);
out += arr("V_mesha", "double", MY.map(C.meshaDay)) + arr("V_nowruz", "double", MY.map(C.nowruzDay));

/* samvatsara + solar hijri */
const SD = [], SY = [], S_I = [], S_SK = [], S_VK = [];
for (let i = 0; i < 8; i++) { const Y = 1995 + Math.floor(rnd() * 45); const d = C.dayNo(Y, 1 + Math.floor(rnd() * 12), 1 + Math.floor(rnd() * 28), 12); const sv = C.samvInfo(d, Y); SD.push(d); SY.push(Y); S_I.push(C.SAMV.indexOf(sv.name)); S_SK.push(sv.saka); S_VK.push(sv.vikrama); }
out += `#define NSV 8\n` + arr("V_svd", "double", SD) + arr("V_svy", "int", SY) + arr("V_svi", "int", S_I) + arr("V_svsk", "int", S_SK) + arr("V_svvk", "int", S_VK);
const SHDv = [], SHYv = [], SH_y = [], SH_m = [], SH_d = [];
for (let i = 0; i < 6; i++) { const Y = 2000 + Math.floor(rnd() * 40); const d = C.dayNo(Y, 1 + Math.floor(rnd() * 12), 1 + Math.floor(rnd() * 28), 12); const r = C.solarHijri(d, Y); SHDv.push(d); SHYv.push(Y); SH_y.push(r.y); SH_m.push(r.mi); SH_d.push(r.d); }
out += `#define NSH 6\n` + arr("V_shd2", "double", SHDv) + arr("V_shy2", "int", SHYv) + arr("V_sh_y", "int", SH_y) + arr("V_sh_m", "int", SH_m) + arr("V_sh_d", "int", SH_d);

/* eclipses 2026 */
{
  const e = C.eclipses(C.dayNo(2026, 1, 1, 12), C.dayNo(2026, 12, 31, 12));
  out += `#define NEC ${e.length}\n`;
  out += arr("V_ec_j", "long", e.map(x => C.jdnOf(x.d)));
  out += arr("V_ec_solar", "int", e.map(x => x.type === "solar" ? 1 : 0));
  out += arr("V_ec_central", "int", e.map(x => x.central ? 1 : 0));
  out += arr("V_ec_dist", "double", e.map(x => x.dist));
}

/* vimshottari */
const VM_S = [], VM_B = [], VM_N = [], VM_L = [], VM_BAL = [], VM_S0 = [];
for (let i = 0; i < 6; i++) { const ms = rnd() * 360, by = 1980 + rnd() * 60; const v = C.vimshottari(ms, by); VM_S.push(ms); VM_B.push(by); VM_N.push(v.nak); VM_L.push(C.NAK ? v.nak % 9 : 0); VM_BAL.push(v.balance); VM_S0.push(v.seq[0].start); }
out += `#define NVM 6\n` + arr("V_vm_ms", "double", VM_S) + arr("V_vm_by", "double", VM_B) + arr("V_vm_nak", "int", VM_N) + arr("V_vm_bal", "double", VM_BAL) + arr("V_vm_s0", "double", VM_S0);

/* telescope (Jupiter) */
const TD = [], T_RA = [], T_DE = [], T_AL = [], T_AZ = [], T_HA = [];
for (let i = 0; i < 5; i++) { const d = rnd() * 12000; const t = C.telescope(C.planetLon("Jupiter", d), 0, d, LAT, LON); TD.push(d); T_RA.push(t.ra); T_DE.push(t.dec); T_AL.push(t.alt); T_AZ.push(t.az); T_HA.push(t.ha); }
out += `#define NT 5\n` + arr("V_td", "double", TD) + arr("V_t_ra", "double", T_RA) + arr("V_t_de", "double", T_DE) + arr("V_t_al", "double", T_AL) + arr("V_t_az", "double", T_AZ) + arr("V_t_ha", "double", T_HA);

/* d2date spot checks */
{
  const dd = [0, 9678.5, -3650, 12345.25];
  out += `#define ND2 ${dd.length}\n` + arr("V_d2", "double", dd);
  out += "static const char*V_d2s[]={" + dd.map(x => JSON.stringify(C.d2date(x))).join(",") + "};\n";
}

/* annual events — full byte parity, two years */
for (const Y of [2026, 2027]) {
  const ev = C.annualEvents(Y);
  const lines = ev.map(e => [e.date, e.name, e.tradition, e.note].join("|"));
  out += `#define NEV${Y} ${lines.length}\n`;
  out += `static const char*V_ev${Y}[]={` + lines.map(l => JSON.stringify(l)).join(",\n") + "};\n";
}

process.stdout.write(out);
